---
# used for publishing the report page on push to main or published release
name: publish site

on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    # only build and deploy the page if the actor is not dependabot
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: false
      - name: Build the report page
        run: |
          uv run --frozen array-we-there-yet report --site_dir=pages
      - name: Deploy the report page
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: pages
          folder: pages
